### ISSUE TITLE
routing: error when routing using framework7 in angular

### ISSUE THREAD

**Issue by tsogtbayar0821** [ashvin777/bower-framework7-angularjs#1]
i was using 31th of July version and then after you update, i am getting error.
when app.router.load({url: url, reloading: false}) : error
when app.router.load({url: url, reloading: true}) : works, but can't use history
here(https://github.com/ashvin777/bower-framework7-angularjs/blob/master/framework7.angular.hook.js#L22)

**Comment by ashvin777** [comment]
Hi Daniel,

When you say history does it mean that caching of the previous screen or window.history ?

Also can you provide more details about this particular problem. May be small snippet of code or the actual error message you are seeing. I will look into this then.

Thanks You.

Regards,
Ashvin
